### ISSUE TITLE
Concurrent Dispatch Queue 

### ISSUE THREAD

**Issue by rva-dev** [robkerr/BlogProjects#1]
Looks like something has changed in swift and the Concurrent Dispatch Queue blog project does not appear to be working anymore as the locationInfo change is no longer detected by the view.

Per blog - locationInfo is a SwiftUI @Published property. Whenever this property is assigned a new value, it triggers a UI update within the SwiftUI View code -  however the progress spinner just stays visible.

**Comment by rva-dev** [comment]
Never mind user error.

**Comment by robkerr** [comment]
Glad you got it working @rva-dev !
